replicaCount: 1

nameOverride: ""
fullnameOverride: "kafka-ui"

image:
  repository: provectuslabs/kafka-ui
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8081
  targetPort: 8080
env:
  KAFKA_CLUSTERS_0_NAME: "prod-cluster"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
  JAVA_OPTS: "-Xmx512m -Xms128m"
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: kafka-ui.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
readiness:
  path: "/"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
liveness:
  path: "/"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
