services:
  kafka:
    image: 'confluentinc/cp-kafka:7.8.0'
    container_name: kafka
    environment:
      # Enables automatic topic creation on the broker.
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KRaft settings
      # The unique identifier for this Kafka node in the cluster.
      KAFKA_NODE_ID: 1
      # Defines the roles of this node. 'broker,controller' means it acts as both a broker and a KRaft controller.
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # The list of voters in the KRaft controller quorum. For a single-node setup, it's just itself.
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # Listener settings
      # The listener name used by the KRaft controller.
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # The listener name for communication between brokers.
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Maps listener names to security protocols.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # The listeners advertised to clients. 'PLAINTEXT://kafka:29092' is for internal communication,
      # and 'PLAINTEXT_HOST://localhost:9092' is for external clients on the host machine.
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092'
      # The listeners that the broker will bind to. Use 0.0.0.0 to listen on all interfaces.
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://kafka:9092'
      # Cluster and topic settings
      # A unique ID for the Kafka cluster, required for KRaft mode.
      # CLUSTER_ID value: docker run --rm -i confluentinc/cp-kafka:7.8.0 sh -c '/bin/kafka-storage random-uuid'
      CLUSTER_ID: 'zre26FiYTIuPmdDVieBJEg'
      # The replication factor for the internal offsets' topic. '1' is required for a single-node setup.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # The replication factor for the transaction state log. '1' is required for a single-node setup.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # The minimum number of in-sync replicas for the transaction state log. '1' is required for a single-node setup.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Development settings
      # The delay before the first rebalance for a consumer group. '0' speeds up startup in development.
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # Sets the root logger level for Kafka's Log4j logging to reduce noise.
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      # Broker-wide maximum message size (10MB)
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      # Must also adjust the replica fetch size to handle the larger messages
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    ports:
      - "9092"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'dev-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    depends_on:
      kafka:
        condition: service_healthy

  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        RUNTIME_JDK_IMAGE: eclipse-temurin:<jdk-version>-alpine
#        RUNTIME_JDK_VERSION: <jdk-version>
    image: demo-app:v1
    environment:
      JAVA_TOOL_OPTIONS: |-
        -XX:+ExitOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/var/dumps
        -XX:MaxRAMPercentage=50
        -Xss256k
        -XX:ReservedCodeCacheSize=64m
        -XX:MaxMetaspaceSize=96m
        -XX:+UseStringDeduplication
        --enable-native-access=ALL-UNNAMED
      KAFKA_CONSUMER_TOPICS: 'dev-in-topic'
      KAFKA_CONSUMER_GROUP_ID: 'dev-group'
      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_PRODUCER_TOPICS: 'dev-out-topic'
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: 'kafka:9092'
      SPRING_APPLICATION_NAME: 'kafka-app-dev'
    command: |-
      --server.shutdown=immediate
      --spring.profiles.active=kafka,dev
      --spring.threads.virtual.enabled=true
      --management.otlp.metrics.export.url=http://otel-lgtm:4318/v1/metrics
      --management.otlp.tracing.transport=http
      --management.otlp.tracing.endpoint=http://otel-lgtm:4318/v1/traces
      --management.otlp.logging.transport=http
      --management.otlp.logging.endpoint=http://otel-lgtm:4318/v1/logs
    ports:
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      kafka:
        condition: service_healthy
      otel-lgtm:
        condition: service_started

  otel-lgtm:
    ## Info: https://github.com/grafana/docker-otel-lgtm
    image: grafana/otel-lgtm:0.13.0
    container_name: otel-lgtm
    restart: unless-stopped
    ports:
      - '3000:3000'   # Grafana UI
      - '4317:4317'   # OTLP gRPC
      - '4318:4318'   # OTLP HTTP
    environment:
      - 'GF_PATHS_DATA=/data/grafana'
      - 'ENABLE_LOGS_ALL=true'
    volumes:
      - otel-lgtm_data:/data

volumes:
  otel-lgtm_data:
    driver: local
