## Kafka Configuration Properties
#spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.client-id=${spring.application.name}
spring.kafka.admin.fail-fast=false
spring.kafka.admin.auto-create=true

## Kafka Consumer Configuration
app.kafka.consumer.topics=${KAFKA_CONSUMER_TOPICS:app-in-topic}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:app-group}
spring.kafka.consumer.bootstrap-servers=${KAFKA_CONSUMER_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Fetch Size Limits (10.5MB = 11010048 bytes)
# Max data returned for a single fetch request across all partitions
spring.kafka.consumer.properties.fetch.max.bytes=11010048
# Max data returned per individual partition
spring.kafka.consumer.properties.max.partition.fetch.bytes=11010048

## Kafka Producer Configuration
app.kafka.producer.topics=${KAFKA_PRODUCER_TOPICS:app-out-topic}
spring.kafka.producer.bootstrap-servers=${KAFKA_PRODUCER_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Limit Retries to 5
spring.kafka.producer.retries=5
# Retry Backoff: The "Offset" or delay between retries
spring.kafka.producer.properties.retry.backoff.ms=500
# Request Timeout: How long to wait for a single request to respond
spring.kafka.producer.properties.request.timeout.ms=5000
# Linger time: The producer groups together any records that arrive in between send calls and batches them in a single request
spring.kafka.producer.properties.linger.ms=20
# Delivery Timeout: This must be greater than linger.ms + request.timeout, setting it to 30 seconds to be safe for 5 retries of 10MB messages
spring.kafka.producer.properties.delivery.timeout.ms=30000
# Request compression algorithm
spring.kafka.producer.properties.compression.type=gzip
# To ensures all replicas acknowledge the message before success
spring.kafka.producer.acks=all
# Ensures the broker skips duplicates if a retry occurs
spring.kafka.producer.properties.enable.idempotence=true
# Batch Size : Maximum size of a batch for a single partition (10MB)
spring.kafka.producer.properties.batch.size=10485760
# Message Size Limits (10MB = 10485760 bytes)
spring.kafka.producer.properties.max.request.size=10485760
# Buffer memory should be larger than the batch.size if you want multiple partitions (64MB)
spring.kafka.producer.buffer-memory=33554432
# Maximum allowed for idempotent producers to maintain ordering
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

## Kafka Observation Configuration
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true

## Actuator configuration
management.endpoints.web.exposure.include=health,info,kafka
management.endpoint.health.show-details=always
