## server configuration
server.port=8080
server.servlet.context-path=/app

## spring configuration
spring.application.name=kafka-app
spring.profiles.active=kafka

## docker compose configuration
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop
