apiVersion: v2
name: demo-kafka-app
description: A minimal Helm chart for demo-app (ported from docker-compose prod)
type: application
version: 0.1.0
appVersion: "v1"
icon: "https://cdn.simpleicons.org/spring"
