apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-credentials
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
type: Opaque
data:
  auth-username: YWRtaW4=       # base64 encoded "admin"
  auth-password: YWRtaW4=       # base64 encoded "admin"
